# https://www.netlify.com/docs/netlify-toml-reference/
[build]
  base = "./"
  publish = "./"
  command = "npm run build"
[[headers]]
  for="/"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000"
    Content-Security-Policy = '''
      default-src 'self';
      base-uri 'self';
      img-src 'self' https://secure.gravatar.com/avatar/ https://i.imgur.com/ https://cdn.kernvalley.us https://*.githubusercontent.com/u/;
      script-src 'self' https://cdn.kernvalley.us;
      style-src 'self' https://cdn.kernvalley.us;
      connect-src 'self' https://cdn.kernvalley.us https://api.kernvalley.us https://api.github.com/users/ https://secure.gravatar.com/avatar/ https://i.imgur.com/ https://*.githubusercontent.com/u/;
      worker-src: 'self';
      font-src 'self' https://cdn.kernvalley.us;
      media-src 'none';
      child-src 'self';
      object-src: 'none';
      manifest-src 'self';
      form-action 'self';
      reflected-xss block;
      block-all-mixed-content;
      upgrade-insecure-requests;
      disown-opener;'''
# [[redirects]]
  # from = ""
  # to = ""
